name:                heavy-logger-instances
version:             0.2.0.1
github:              "portnov/heavy-logger"
license:             BSD3
author:              "Ilya Portnov"
maintainer:          "portnov84@rambler.ru"
copyright:           "2018 Ilya Portnov"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:         Orphan instances for data types in heavy-logger package
description: |
      This package contains orphan instances for data types in heavy-logger package for:
      * Binary type class (from binary package)
      * MonadThrow, MonadCatch, MonadMask type classes (from exceptions package) for LoggingT transformer.

category:            System

dependencies:
- base >= 4.7 && < 5
- mtl
- heavy-logger >= 0.3.2.0
- binary
- exceptions
- text >= 1.2
- text-format-heavy >= 0.1.5.1
- hsyslog >= 5.0.1
- template-haskell >= 2.12.0.0

library:
  source-dirs: src

tests:
  binary-test:
    main: Binary.hs
    source-dirs: tests
    dependencies:
      - heavy-logger-instances

