name:                heavy-logger-instances
version:             0.1.0.0
github:              "portnov/heavy-logger"
license:             BSD3
author:              "Ilya Portnov"
maintainer:          "portnov84@rambler.ru"
copyright:           "2018 Ilya Portnov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Orphan instances for data types in heavy-logger package
category:            System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Orphan instances for data types in heavy-logger package

dependencies:
- base >= 4.7 && < 5
- heavy-logger >= 0.3.2.0
- binary
- exceptions
- text >= 1.2
- text-format-heavy >= 0.1.5.1
- hsyslog >= 5.0.1
- template-haskell >= 2.12

library:
  source-dirs: src

tests:
  binary-test:
    main: Binary.hs
    source-dirs: tests
    dependencies:
      - heavy-logger-instances

